FROM alpine:latest as builder
WORKDIR /opt/vsearch
COPY . .
RUN apk add --no-cache \
        libstdc++ zlib-dev bzip2-dev \
        autoconf automake make g++ 
RUN ./autogen.sh && \
    ./configure CFLAGS="-O3" CXXFLAGS="-O3" --prefix=/install && \
    make clean && \
    make -j8 && \
    make install

FROM alpine:latest as package
RUN apk add --no-cache \
        libstdc++ g++
COPY --from=builder /install /install
